name: Add to OSS board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - labeled

permissions: {}

jobs:

  run:
    uses: "anchore/workflows/.github/workflows/oss-project-board-add.yaml@a71346be63db56f324237b6a35fd35ffcec6d737" # @main
    secrets:
      token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
